### ISSUE TITLE
Octave - 2?

### ISSUE THREAD

**Issue by postacik** [ghost23/music_notes#1]
Hi,

What is the reason of subtracting 2 from the octave value of the note specified in XML?

```dart
Pitch? parsePitchXML(XmlElement pitchXML) {
  final stepElmt = pitchXML.getElement('step');
  final String? stepString = stepElmt?.innerText;
  final BaseTones? step = stepString != null
      ? BaseTones.values
          .firstWhere((e) => e.toString() == 'BaseTones.$stepString')
      : null;

  final octaveElmt = pitchXML.getElement('octave');
  final int? octave =
      octaveElmt != null ? int.parse(octaveElmt.innerText) : null;

  final alterElmt = pitchXML.getElement('alter');
  final int? alter = alterElmt != null ? int.parse(alterElmt.innerText) : null;

  if (step != null && octave != null) {
    return Pitch(step, octave - 2, alter);
  } else {
    return null;
  }
}

```

**Comment by ghost23** [comment]
The reason is, that my current Rendering system currently has a different view on what the zero octave is compared to musicXML. For me,  c' is the zero octave, whereas for musicxml it is different.

The reason for this difference is that I started building the renderer before I started thinking about musicxml.

**Comment by postacik** [comment]
Does this mean, if I add pitches manually by code (not by parsing a musicxml file), I should substract 2 from the octave I intend to display?

**Comment by ghost23** [comment]
If you intend to use the same idea of numeric octave level like musicxml does, then yes.

**Comment by postacik** [comment]
Ok, thanks

**Comment by postacik** [comment]
This is a well thought and coded library with a beautiful output. Thanks for sharing...
